### ISSUE TITLE
When time date is changed to a previous date, journal fails and Dev-app log gets incorrect

### ISSUE THREAD

**Issue by otaviobp** [solettaproject/soletta-dev-app#60]
When edison board reboots the date changes to a factory default and Dad journal stop working.

**Comment by brunobottazzini** [comment]
Adding log message error from systemd journalctl:
`Failed to get realtime timestamp: Cannot assign requested address`

**Comment by brunobottazzini** [comment]
Since this problem is not from Dev-App and yet it is a problem that have come from Systemd, we should close this issue.

Also, after a massive testing that we have done in upgraded images. 

We could not replicate the problem after upgrading the systemd from v216 (The image we have found the problem) to v229 (newest version).

After some resarch we have found  that this bug was fixed in version v219 as you can see in the followings:
https://bugzilla.redhat.com/show_bug.cgi?id=1253649
and
https://github.com/systemd/systemd/pull/958

**Comment by otaviobp** [comment]
I tried to reproduce this error in newer images, but I couldn't. It seems to be fixed.
