### ISSUE TITLE
cannot save modification of a file by click "save current file" button

### ISSUE THREAD

**Issue by otcyanglei** [solettaproject/soletta-dev-app#79]
The "save current file" button does not work when trying to save the modification of a file. 
I reload the file, the changes cannot be saved always. 

Environment: v1_beta7

**Comment by brunobottazzini** [comment]
What file have you tried to save ? Any file ?

**Comment by bdilly** [comment]
Steps:
1. launch a web browser and input address
2. open a fbp file from demo and modify in code viewer
3. click save button
3. open the same fbp file and modification is not save

**Comment by bdilly** [comment]
So it's really about demo files edition.
We don't want to allow users to overwrite these files, so I would suggest to disable "Save" options as a fix for this issue.

**Comment by brunobottazzini** [comment]
As suggested by @bdilly, the fix was proposed here: https://github.com/solettaproject/soletta-dev-app/pull/83/commits/f9f011a47394bcb0c04b4e0439a20e56e0f69ce1

**Comment by otcyanglei** [comment]
Sorry for comment late.
How about new file saving? if I just type fbp codes in editor, and click "save" button. 
I suppose it will be saved on disk. 
However, the fixing above seems not covering this correctly.

**Comment by brunobottazzini** [comment]
@otcyanglei, with this patch the save button will be disabled when you are coding directly (without opening a file). 

You will need to create a project, if you want to save a file. 

But, you are right we should allow to save the files and creating the project when saving for the first time.

I will close this issue since the behavior of the save is okay now, and create a new task for this new feature :+1:

**Comment by brunobottazzini** [comment]
Task created: https://github.com/solettaproject/soletta-dev-app/issues/85

Thanks
