### ISSUE TITLE
Cheat-Sheet : "Get the Code" button not visible

### ISSUE THREAD

**Issue by preetham** [solettaproject/soletta-dev-app#84]
In the new design, after selecting a nodetype "Get the Code" button is not visible after the image loads.
![screenshot from 2016-04-16 19-52-47](https://cloud.githubusercontent.com/assets/9149028/14581529/053756ba-040d-11e6-88ec-3d84b1c3f38f.png)

**Comment by brunobottazzini** [comment]
I can see this button here, what browser are you using ? 

Also since this is an iframe the new design wouldn't interfere in the copy code button, this doesn't make sense.

![screenshot from 2016-04-18 09 54 52](https://cloud.githubusercontent.com/assets/4460234/14604799/c612c038-054b-11e6-8513-76a351d7f414.png)

**Comment by preetham** [comment]
I'm using Google Chrome 49 and I think this issue is caused due to the new top bar making the nodetype div smaller. If we minimize the page to 75% (my resolution is 1366x768) 
![screenshot from 2016-04-18 21-30-16](https://cloud.githubusercontent.com/assets/9149028/14611013/df3dd89c-05ad-11e6-82c2-6bf5ced71503.png) we can see "Get the code" button clearly.
One of the options for a possible fix is a scroll bar for the nodetype div.

**Comment by brunobottazzini** [comment]
Yes, I can confirm this. I resized my windows and the get the code button got hidden. The div that contains this button should contain a scrollbar

**Comment by brunobottazzini** [comment]
Just tested and the issue was fixed.
http://solettaproject.github.io/docs/nodetypes

Thanks
